"""empty message

Revision ID: 2eb1d5ab6159
Revises: bdaf290ec182
Create Date: 2020-06-17 19:24:42.246020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb1d5ab6159'
down_revision = 'bdaf290ec182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('screen_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tweet', sa.Column('embedding', sa.PickleType(), nullable=True))
    op.add_column('tweet', sa.Column('full_text', sa.String(length=500), nullable=True))
    op.add_column('tweet', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'tweet', 'user', ['user_id'], ['id'])
    op.drop_column('tweet', 'user')
    op.drop_column('tweet', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('text', sa.VARCHAR(length=280), nullable=True))
    op.add_column('tweet', sa.Column('user', sa.VARCHAR(length=15), nullable=True))
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.drop_column('tweet', 'user_id')
    op.drop_column('tweet', 'full_text')
    op.drop_column('tweet', 'embedding')
    op.drop_table('user')
    # ### end Alembic commands ###
